site_name: Distributed

nav:
  - Home: index.md
  - Model class: model.md
  - Velocity class: velocity.md
  - Level class: level.md
  - Reinit class: reinit.md

theme:
  name: material
  favicon: coffee.ico
  logo: coffee.ico
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: orange
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: pink



markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true


extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            show_root_full_path: false
            show_source: true



